### ISSUE TITLE
Are the recent changes only for Arduino?

### ISSUE THREAD

**Issue by kolalde** [BareConductive/mpr121#12]
Hi,

I'm currently using this library on an ESP8266 and just noticed the most recent change from a couple weeks ago talks about EEPROM (I've not read the changes yet, just lightly skimmed).  

So, basically the library currently works on ESP8266, so you know if that has change with the recent update?

Thanks for the work!

**Comment by loosepascal** [comment]
Hi kolalde,

We've just updated the code because before, the code didn't work with ESP8266, but now it does, so you can update it if you want to!
