### ISSUE TITLE
Raspberry Pi + Buster Python3 import MPR121 error

### ISSUE THREAD

**Issue by clovenguth** [BareConductive/mpr121#13]
I've just discovered tonight both doing an update from Stretch to Buster on once working python3 import MPR121 and from a fresh install on a completely different Pi and PiCap that import MPR121 errors out only in Python3. Python2.7 works fine.

Also confirmed with all the latest update on Stretch system that Python3 import MPR121 still works.

Error:

XXXXX:~ $ python3
Python 3.7.3 (default, Apr 3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import MPR121
Traceback (most recent call last):
File "", line 1, in 
ModuleNotFoundError: No module named 'MPR121'

**Comment by loosepascal** [comment]
Sorry, I've just seen this. Were you able to resolve this issue? If not can you send us an email at info@bareconductive.com? I'm going to close this issue because it is not related to this repository.
