### ISSUE TITLE
Two MPR121 Boards with different I2C Adresses

### ISSUE THREAD

**Issue by flow1986** [BareConductive/mpr121#14]
Hi,
is it possbile to Control 2 MPR121 Boards with different I2C Adresses?
i need 24 Touch Inputs and therefor one MPR121 Board isn´t enough...

Thanks for your Reply!

Flo

**Comment by stefandz** [comment]
Hi Flo

It is possible to call MPR121.begin with various arguments, including the I2C address - i.e. `MPR121.begin( 0x5A )`. Take a look at MPR121.h in this library. By default, a single MPR121 object is instantiated. If you want to use more than one, you can declare another like this:

```
MPR121_type MPR121_number_2;
MPR121_number_2.begin( 0x5B);
```

I hope this helps

Stefan

**Comment by flow1986** [comment]
that helped a lot!
thanks
