### ISSUE TITLE
Output value for approach

### ISSUE THREAD

**Issue by maxholgasson** [BareConductive/mpr121#3]
Hi is it possible to measure a value corresponding how far the finger is near the sensor?

I have different pads that varies in size and how far they are placed behind the surface which can be touched. So I would like to analyze the different values

**Comment by stefandz** [comment]
Have you tried the [datastream](https://github.com/BareConductive/mpr121/tree/public/MPR121/Examples/DataStream) example in this library?

**Comment by maxholgasson** [comment]
Thanks for the hint! That helps :)
