### ISSUE TITLE
Separate touch and release trip thresholds for each electrode?

### ISSUE THREAD

**Issue by tonysnark** [BareConductive/mpr121#7]
Readme calls out the feature "Separate touch and release trip thresholds for each electrode"

I don't see any examples on simpletouch.ino how to address individual electrode thresholds, only overall thresholds with:

`  MPR121.setTouchThreshold(40);`

Thanks in advance for any insight.

**Comment by stefandz** [comment]
Hi Tony

The syntax for setting separate touch and release thresholds is detailed in the class header [here](https://github.com/BareConductive/mpr121/blob/public/MPR121/MPR121.h#L254-L260)

`MPR121.setTouchThreshold( electrodeNumber, thresholdValue );`

Hope this helps

S
